AzureScimitar:
  name: "Azure Scimitar"
  allowDualWield: true
  duration: 18

  slash-1:
    attackType: SLASH
    blank: false
    arcRadius: 1.4
    cooldown: 0.35
    detail: 55
    layers: 3
    layerSpace: 0.22
    layerColors:
      - "rgb(40, 40, 180)"
      - "rgb(80, 80, 220)"
      - "rgb(140, 140, 255)"
    particleSize: [0.8, 1.0, 1.2]
    damage: 3.0
    delay: 5
    rotation: -150
    jitter: 4
    distanceFromPlayer: 1.1
    sound: ["entity.player.attack.sweep", "1", "1.0"]
    originAboveHead: 0
    horizontalRotation: -10
    horizontalOffset: 0
    damageRegion: 1.0

  blank-2:
    attackType: BLANK
    blank: true
    cooldown: 0.35

  slash-3:
    attackType: SLASH
    blank: false
    arcRadius: 1.5
    cooldown: 0.35
    detail: 60
    layers: 3
    layerSpace: 0.25
    layerColors:
      - "rgb(40, 40, 180)"
      - "rgb(100, 100, 240)"
      - "rgb(160, 160, 255)"
    particleSize: [0.9, 1.2, 1.4]
    damage: 3.2
    delay: 6
    rotation: -90
    jitter: 6
    distanceFromPlayer: 1.2
    sound: ["entity.player.attack.sweep", "1", "1.1"]
    originAboveHead: 0
    horizontalRotation: 12
    horizontalOffset: 0
    damageRegion: 1.0

  slash-4:
    attackType: SLASH
    blank: false
    arcRadius: 1.6
    cooldown: 0.35
    detail: 60
    layers: 3
    layerSpace: 0.25
    layerColors:
      - "rgb(60, 60, 200)"
      - "rgb(120, 120, 240)"
      - "rgb(180, 180, 255)"
    particleSize: [1.0, 1.3, 1.5]
    damage: 3.4
    delay: 6
    rotation: -45
    jitter: 6
    distanceFromPlayer: 1.25
    sound: ["entity.player.attack.sweep", "1", "1.15"]
    originAboveHead: 0
    horizontalRotation: -14
    horizontalOffset: 0
    damageRegion: 1.0

  thrust-5:
    attackType: THRUST
    blank: false
    damageRegion: 1.0
    thrustStrength: 1.3
    thrustDelay: 4
    damage: 3.6
    length: 40
    sound: ["entity.player.attack.sweep", "1", "1.4"]
    gradient:
      - "rgb(200, 40, 40)"
      - "rgb(40, 40, 180)"
    handleColor: "rgb(200, 40, 40)"
    cooldown: 0.35
    startRadius: 0.45

#

CrimsonScimitar:
  name: "Crimson Scimitar"
  allowDualWield: true
  duration: 18

  blank-1:
    attackType: BLANK
    blank: true
    cooldown: 0.35

  slash-2:
    attackType: SLASH
    blank: false
    arcRadius: 1.3
    cooldown: 0.35
    detail: 55
    layers: 3
    layerSpace: 0.22
    layerColors:
      - "rgb(180, 40, 40)"
      - "rgb(220, 60, 60)"
      - "rgb(255, 120, 120)"
    particleSize: [0.8, 1.0, 1.2]
    damage: 2.8
    delay: 5
    rotation: -45
    jitter: 4
    distanceFromPlayer: 1.1
    sound: ["entity.player.attack.sweep", "1", "1.0"]
    originAboveHead: 0
    horizontalRotation: 10
    horizontalOffset: 0
    damageRegion: 1.0

  blank-3:
    attackType: BLANK
    blank: true
    cooldown: 0.35

  slash-4:
    attackType: SLASH
    blank: false
    arcRadius: 1.5
    cooldown: 0.35
    detail: 60
    layers: 3
    layerSpace: 0.25
    layerColors:
      - "rgb(200, 40, 40)"
      - "rgb(240, 80, 80)"
      - "rgb(255, 160, 160)"
    particleSize: [0.9, 1.2, 1.4]
    damage: 3.0
    delay: 6
    rotation: 45
    jitter: 6
    distanceFromPlayer: 1.2
    sound: ["entity.player.attack.sweep", "1", "1.1"]
    originAboveHead: 0
    horizontalRotation: -12
    horizontalOffset: 0
    damageRegion: 1.0

  blank-5:
    attackType: BLANK
    blank: true
    cooldown: 0.35


